server:
  port: 8080

executors:
  items:
    order-executor:
      coreSize: 20
      maxSize: 100
      queueSize: 2000
      keepAliveSeconds: 1000
      rejectedPolicy: CALLER_RUNS
      tags: [order, api]

bulkheads:
  items:
    - name: order-create
      rule:
        api: order.create
      limit: 50

ratelimits:
  - name: order-api
    rule:
      api: order.create
    qps: 200

timeouts:
  - name: order-api
    rule:
      api: order.create
    timeoutMs: 300


management:
  endpoints:
    web:
      exposure:
        include: prometheus



