server:
  port: 8080

executors:
  order:
    coreSize: 20
    maxSize: 50
    queueSize: 1000
    rejectPolicy: CALLER_RUNS
    tags: [order, api]

management:
  endpoints:
    web:
      exposure:
        include: prometheus
